### ISSUE TITLE
Make slider photo bigger

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/8planner-web#28]
![image](https://user-images.githubusercontent.com/30463117/163942479-b8311c5e-1f9c-4e0b-a74a-d138a4c069de.png)

**Comment by russel0907** [comment]
Make slider photo bigger;

##Default Screen
![Screenshot (273)](https://user-images.githubusercontent.com/94702093/164005240-cc584e4f-8103-411e-baa7-fcb2b5cca6f3.png)

##Ipad S
![Screen Shot 2022-04-19 at 20 35 59](https://user-images.githubusercontent.com/94702093/164005409-5b2e4f1a-7d46-440d-bae1-4cb4606d8baa.png)
creen

##Mobile Screen
![Screenshot (274)](https://user-images.githubusercontent.com/94702093/164005443-feb30897-4e13-46f0-95a7-68203178599b.png)
