### ISSUE TITLE
Make photo change based on selected tab

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/8planner-web#30]
![image](https://user-images.githubusercontent.com/30463117/164157666-b7ac9378-5a75-4aa3-8b37-dbb8127c76a8.png)

**Comment by russel0907** [comment]
Make photo change based on selected tab;

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/94702093/164610861-f74ed1bb-34e1-4c47-a46a-8a189b06a473.gif)
