### ISSUE TITLE
Change contact form design

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/8planner-web#33]
Paraphrase the copy-writing on the right side, redesign the contact form to match with website overall design.

Redesign contact form similarly as below:

Input field: `Name` `Email` `Phone number`
Button: `Submit`
![image](https://user-images.githubusercontent.com/30463117/165006232-f91363e7-5164-4582-aea0-6f29ab56b9db.png)

**Comment by russel0907** [comment]
Change contact form design;

![Screenshot 2022-04-25 at 22-13-51 8Planner - Contract Management System](https://user-images.githubusercontent.com/94702093/165108194-cd8ae5e3-f4ef-4d41-898f-01ad050c9b79.png)
