### ISSUE TITLE
Add KL partners oaktree to contact

### ISSUE THREAD

**Issue by paragasu** [phisoft/8planner-web#37]
https://www.oaktree.com.my/contact-us

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/166100047-d61b792a-5077-47d5-9f12-277e95480751.png">

**Comment by russel0907** [comment]
Add KL partners oaktree to contact;

![Screenshot (305)](https://user-images.githubusercontent.com/94702093/167095155-5c5630ed-0bb7-4324-bcb4-c74fa7894c63.png)
