### ISSUE TITLE
Add OakTree contact info

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/8planner-web#46]
- [x] Redesign the footer for various dimensions (tablet, mobile)
- [x] Add OakTree contact info

`Email`
info@oaktree.com.my

`Phone`
+6012 520 8575

8Planner web on mobile view:
![Screen Shot 2022-05-10 at 09 27 58](https://user-images.githubusercontent.com/30463117/167524399-7571bf58-feb8-4fbe-aef1-cdcc8b79f979.png)

8Planner web on tablet view
![Screen Shot 2022-05-10 at 09 29 00](https://user-images.githubusercontent.com/30463117/167524635-f1ddb428-4ec2-4368-960c-b41e9a8bca74.png)

**Comment by russel0907** [comment]
Add OakTree contact info;

Fix responsiveness;

# Web View
![Screenshot (320)](https://user-images.githubusercontent.com/94702093/167643711-a5217ae2-aa88-43e4-85b8-b774946eb335.png)

# Ipad View
![Screenshot (319)](https://user-images.githubusercontent.com/94702093/167643765-44ac77f9-3695-44db-b80c-d329d9903c90.png)

# Mobile View
![Screenshot (318)](https://user-images.githubusercontent.com/94702093/167643795-04f090d4-a6b3-4a9a-84d8-64be62a81f4e.png)
