### ISSUE TITLE
Change app screenshot still showing pestplanner

### ISSUE THREAD

**Issue by paragasu** [phisoft/8planner-web#54]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/173072964-11bacb2a-8279-46e6-a18e-37c4f43a9e3b.png">

**Comment by russel0907** [comment]
Update app screenshot;

![Screenshot 2022-06-11 at 10-06-08 8Planner - Contract Management System](https://user-images.githubusercontent.com/94702093/173168592-044253e3-60ed-43f7-9f9b-1bd68df505dd.png)

**Comment by russel0907** [comment]
## latest update

1. update app screenshot's using slider to show features 

## Updated app screenshot

https://user-images.githubusercontent.com/94702093/173178474-549fe80e-ac85-40fb-8a84-be8d74407b2a.mp4
