### ISSUE TITLE
Change header screenshot to latest version

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/8planner-web#56]
Go to demo.8planner.com, fill in the a few demo data and proceed to edit the system screenshot with the latest version.

![image](https://user-images.githubusercontent.com/30463117/173474838-e0ed89f7-0f89-4b1b-8d01-6da7658733fe.png)

**Comment by russel0907** [comment]
Change header screenshot to latest version #56

1.Optimize image size and resolution
2. Update screenshot to latest version


## Web view
![Screenshot 2022-06-14 at 10-55-18 8Planner - Contract Management System](https://user-images.githubusercontent.com/94702093/173484563-9c451cb7-f14a-469d-940c-9f6a0069afef.png)


## Mobile view
![Screenshot 2022-06-14 at 11-01-44 8Planner - Contract Management System](https://user-images.githubusercontent.com/94702093/173484587-10b488ef-ea22-4d44-b92a-716358128fce.png)
