### ISSUE TITLE
Hide `8leave` & `8membership`

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/8planner-web#64]
- [x] hide modules on 8leave & 8membership
- [x] hide any features related to 8leave & 8membership

![image](https://user-images.githubusercontent.com/30463117/177450697-35d8c62b-1df5-45df-bb5e-eb2d016b53a3.png)
![image](https://user-images.githubusercontent.com/30463117/177450757-55611392-2629-418b-9a0e-860dd03b822d.png)

**Comment by russel0907** [comment]
Hide any part that related to the 8leave & 8membership

## hide tab section that contains 8leave and 8membership desc
![8Planner-Service-and-schedule-planner](https://user-images.githubusercontent.com/94702093/177512347-aeea2aa9-a9ef-4f8d-b436-1f92578c1a7d.png)

## hide details that contains 8leave and 8membership in apps section
![Screenshot 2022-07-06 at 16-57-19 8Planner - Service and schedule planner](https://user-images.githubusercontent.com/94702093/177512608-83c31043-0d8f-483e-a90b-461316062021.png)
