### ISSUE TITLE
Optimize SEO for website

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/8planner-web#66]

**Comment by russel0907** [comment]
## Add meta for keywords
![code](https://user-images.githubusercontent.com/94702093/178894772-c2dae8e2-ecbd-4190-b525-4068f9c83dae.png)

## add title description on the section for system screenshot's
![Screenshot 2022-07-14 at 11-56-15 8Planner - Service and schedule planner](https://user-images.githubusercontent.com/94702093/178895048-d403ffb1-ff12-4a13-b4e9-1483768975a6.png)
